/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import org.slf4j.LoggerFactory;

import org.slf4j.Logger;

public class App {
private static final Logger LOGGER = LoggerFactory.getLogger(App.class);
    public static void main(String[] args) {

        LOGGER.debug("Requisição recebida do IP: {}", "192.168.1.1");
        LOGGER.info("Usuário: {}", "juca");
        LOGGER.warn("Conexão perdida com banco de dados. Tentando novamente");
        LOGGER.error("Falha ao escrever {} no arquivo {}", 123, "matriculas.txt");

        Pessoa p = new Pessoa("Caio", "13142412515-21");



        System.out.println(p.getCpf());
        System.out.println(p.getNome());
        System.out.println(p.hashCode());
        System.out.println(p.toString());
    }
}
